echo "----------------------------------------"
echo "     Welcome to Mittel Installer!       "
echo "----------------------------------------"
echo ""
echo "This script will install Mittel on your system."
echo ""
echo "Press ENTER to continue or Ctrl-C to abort."
read -p ""
echo ""
echo "Installing..."

